# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'chrome.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

icons = {"Password":"icons/key.png", "History":"icons/history.png", "Cookies":"icons/cookie.png", "Cache":"icons/accounting.png", "Bookmarks":"icons/notebook.png"}
icons.setdefault("Cache")

class general_apps_ui(object):
    def setupUi(self, MainWindow, tree_items, name):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(702, 433)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.treeWidget = QtGui.QTreeWidget(self.centralwidget)
        self.treeWidget.setSelectionMode(QtGui.QAbstractItemView.ContiguousSelection)
        self.treeWidget.setIndentation(0)
        self.treeWidget.setObjectName(_fromUtf8("treeWidget"))
        for it in tree_items:
            item_0 = QtGui.QTreeWidgetItem(self.treeWidget)
            icon = QtGui.QIcon()
            icon_path = icons[it[1]]
            icon.addPixmap(QtGui.QPixmap(_fromUtf8(icon_path)), QtGui.QIcon.Normal, QtGui.QIcon.Off)
            item_0.setIcon(0, icon)
            item_0.setText(0, _translate("MainWindow", name + " " + it[1], None))
        self.treeWidget.header().setVisible(True)
        self.treeWidget.header().setDefaultSectionSize(200)
        self.treeWidget.header().setMinimumSectionSize(200)
        self.treeWidget.header().setSortIndicatorShown(True)
        self.treeWidget.header().setStretchLastSection(False)
        self.verticalLayout.addWidget(self.treeWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 702, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuEdit = QtGui.QMenu(self.menubar)
        self.menuEdit.setObjectName(_fromUtf8("menuEdit"))
        self.menuView = QtGui.QMenu(self.menubar)
        self.menuView.setObjectName(_fromUtf8("menuView"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.actionSave_Selected_Items = QtGui.QAction(MainWindow)
        self.actionSave_Selected_Items.setObjectName(_fromUtf8("actionSave_Selected_Items"))
        self.actionFind = QtGui.QAction(MainWindow)
        self.actionFind.setObjectName(_fromUtf8("actionFind"))
        self.actionSelect_All = QtGui.QAction(MainWindow)
        self.actionSelect_All.setObjectName(_fromUtf8("actionSelect_All"))
        self.actionDeselect_All = QtGui.QAction(MainWindow)
        self.actionDeselect_All.setObjectName(_fromUtf8("actionDeselect_All"))
        self.actionRefresh = QtGui.QAction(MainWindow)
        self.actionRefresh.setObjectName(_fromUtf8("actionRefresh"))
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.actionTurorial = QtGui.QAction(MainWindow)
        self.actionTurorial.setObjectName(_fromUtf8("actionTurorial"))
        self.menuFile.addAction(self.actionSave_Selected_Items)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuEdit.addAction(self.actionFind)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionSelect_All)
        self.menuEdit.addAction(self.actionDeselect_All)
        self.menuView.addAction(self.actionRefresh)
        self.menuHelp.addAction(self.actionAbout)
        self.menuHelp.addAction(self.actionTurorial)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow, name)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow, name):
        MainWindow.setWindowTitle(_translate("MainWindow", name, None))
        self.treeWidget.setSortingEnabled(True)
        self.treeWidget.headerItem().setText(0, _translate("MainWindow", "Programs", None))
        __sortingEnabled = self.treeWidget.isSortingEnabled()
        self.treeWidget.setSortingEnabled(False)
        self.treeWidget.setSortingEnabled(__sortingEnabled)
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit", None))
        self.menuHelp.setTitle(_translate("MainWindow", "Help", None))
        self.menuView.setTitle(_translate("MainWindow", "View", None))
        self.actionExit.setText(_translate("MainWindow", "Exit", None))
        self.actionSave_Selected_Items.setText(_translate("MainWindow", "Save Selected Items", None))
        self.actionFind.setText(_translate("MainWindow", "Find", None))
        self.actionSelect_All.setText(_translate("MainWindow", "Select All", None))
        self.actionDeselect_All.setText(_translate("MainWindow", "Deselect All", None))
        self.actionRefresh.setText(_translate("MainWindow", "Refresh", None))
        self.actionAbout.setText(_translate("MainWindow", "About", None))
        self.actionTurorial.setText(_translate("MainWindow", "Tutorial", None))


class general_ui(object):
    def setupUi(self, MainWindow, tree_items, name):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(890, 542)
        MainWindow.setToolTip(_fromUtf8(""))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.treeWidget = QtGui.QTreeWidget(self.centralwidget)
        self.treeWidget.setToolTip(_fromUtf8(""))
        self.treeWidget.setStatusTip(_fromUtf8(""))
        self.treeWidget.setAutoScroll(True)
        self.treeWidget.setProperty("showDropIndicator", True)
        self.treeWidget.setAlternatingRowColors(False)
        self.treeWidget.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.treeWidget.setIndentation(0)
        self.treeWidget.setItemsExpandable(True)
        self.treeWidget.setObjectName(_fromUtf8("treeWidget"))
        self.treeWidget.header().setDefaultSectionSize(150)
        self.treeWidget.header().setMinimumSectionSize(150)
        self.treeWidget.header().setSortIndicatorShown(True)
        self.treeWidget.header().setStretchLastSection(False)
        self.horizontalLayout.addWidget(self.treeWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 890, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuEdit = QtGui.QMenu(self.menubar)
        self.menuEdit.setObjectName(_fromUtf8("menuEdit"))
        self.menuView = QtGui.QMenu(self.menubar)
        self.menuView.setObjectName(_fromUtf8("menuView"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setSizeGripEnabled(True)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        lab = QtGui.QLabel(MainWindow)
        lab.setText("yooooooooooooooooooooooooooo")
        self.statusbar.addWidget(lab)
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.actionSave_Selected_Items = QtGui.QAction(MainWindow)
        self.actionSave_Selected_Items.setObjectName(_fromUtf8("actionSave_Selected_Items"))
        self.actionFind = QtGui.QAction(MainWindow)
        self.actionFind.setObjectName(_fromUtf8("actionFind"))
        self.actionSelect_All = QtGui.QAction(MainWindow)
        self.actionSelect_All.setObjectName(_fromUtf8("actionSelect_All"))
        self.actionDeselect_All = QtGui.QAction(MainWindow)
        self.actionDeselect_All.setObjectName(_fromUtf8("actionDeselect_All"))
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.actionRefresh = QtGui.QAction(MainWindow)
        self.actionRefresh.setObjectName(_fromUtf8("actionRefresh"))
        self.actionTurorial = QtGui.QAction(MainWindow)
        self.actionTurorial.setObjectName(_fromUtf8("actionTurorial"))
        self.actionRefresh = QtGui.QAction(MainWindow)
        self.actionRefresh.setObjectName(_fromUtf8("actionRefresh"))
        self.menuFile.addAction(self.actionSave_Selected_Items)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuEdit.addAction(self.actionFind)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionSelect_All)
        self.menuEdit.addAction(self.actionDeselect_All)
        self.menuView.addAction(self.actionRefresh)
        self.menuHelp.addAction(self.actionAbout)
        self.menuHelp.addAction(self.actionTurorial)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.retranslateUi(MainWindow, tree_items, name)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow, tree_items, name):
        MainWindow.setWindowTitle(_translate("MainWindow", name[0] + " " + name[1], None))
        self.treeWidget.setSortingEnabled(True)
        for item in tree_items:
            self.treeWidget.headerItem().setText(item[0], _translate("MainWindow", str(item[1]), None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit", None))
        self.menuHelp.setTitle(_translate("MainWindow", "Help", None))
        self.menuView.setTitle(_translate("MainWindow", "View", None))
        self.actionExit.setText(_translate("MainWindow", "Exit", None))
        self.actionSave_Selected_Items.setText(
            _translate("MainWindow", "Save Selected Items", None))
        self.actionSave_Selected_Items.setIconText(
            _translate("MainWindow", "Save Selected Items", None))
        self.actionFind.setText(_translate("MainWindow", "Find", None))
        self.actionSelect_All.setText(_translate("MainWindow", "Select All", None))
        self.actionDeselect_All.setText(_translate("MainWindow", "Deselect All", None))
        self.actionAbout.setText(_translate("MainWindow", "About", None))
        self.actionTurorial.setText(_translate("MainWindow", "Tutorial", None))
        self.actionRefresh.setText(_translate("MainWindow", "Refresh", None))
